# =============================================================================
# Docker Compose Configuration for Project Aether
# Development environment with hot reload and debugging enabled
# =============================================================================

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: projectaether
      POSTGRES_USER: aether_user
      POSTGRES_PASSWORD: aether_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether_user -d projectaether"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # Development environment variables (override in production)
      - DATABASE_URL=postgresql://aether_user:aether_pass@db:5432/projectaether
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      
      # Google Cloud configuration (for production deployment)
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-}
      - GCP_REGION=${GCP_REGION:-us-central1}
      - CLOUD_SQL_CONNECTION_NAME=${CLOUD_SQL_CONNECTION_NAME:-}
      - MEMORYSTORE_IP=${MEMORYSTORE_IP:-}
      - DATABASE_USER=${DATABASE_USER:-aether_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-aether_pass}
      - DATABASE_NAME=${DATABASE_NAME:-projectaether}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build: ./backend
    environment:
      # Development environment variables (override in production)
      - DATABASE_URL=postgresql://aether_user:aether_pass@db:5432/projectaether
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      
      # Google Cloud configuration (for production deployment)
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-}
      - GCP_REGION=${GCP_REGION:-us-central1}
      - CLOUD_SQL_CONNECTION_NAME=${CLOUD_SQL_CONNECTION_NAME:-}
      - MEMORYSTORE_IP=${MEMORYSTORE_IP:-}
      - DATABASE_USER=${DATABASE_USER:-aether_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-aether_pass}
      - DATABASE_NAME=${DATABASE_NAME:-projectaether}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: celery -A app.tasks worker --loglevel=info --concurrency=2

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - api

volumes:
  postgres_data:
